#!/usr/bin/env bash
#A script that accepts a string as an argument and ping the IP  5 times
IP_ADDRESS=$1

if [[ $# -eq 0 ]]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi

#ping the address multiple time usin -c option
ping -c 5 "$IP_ADDRESS"
